services:
  app:
    container_name: paper_portfolio
    build:
      context: .
      dockerfile: Dockerfile
    image: node:lts
    ports:
      - 4321:4321
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./:/app
